# *************************************************************************
# * Copyright (c) 2022, 2023 Hannes Wellmann and others.
# *
# * This program and the accompanying materials are made available under
# * the terms of the Eclipse Public License 2.0 which accompanies this
# * distribution, and is available at https://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# *      Hannes Wellmann - initial API and implementation
# *************************************************************************

name: 'Check license vetting status'
description: 'Checks if the licenses of all dependencies are vetted and requests a review in case required and wanted'
inputs:
  request-review:
    description: ''
    required: false
  project-id:
    description: ''
    required: false
outputs:
  licenses-vetted: 
    description: "True if all licenses are vetted, else false"
    value: ${{ steps.license-check-with-review-request.outputs.build-succeeded }}
runs:
  using: "composite"
  steps:
    - id: license-check-with-review-request
      shell: bash {0} # do not fail-fast
      run: |
        mvnArgs="-U -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true --settings $GITHUB_ACTION_PATH/licenseCheckMavenSettings.xml"
        if [ ${{ inputs.request-review }} ]; then
          mvn ${mvnArgs} -Ddash.iplab.token=$GITLAB_API_TOKEN -Ddash.projectId=${{ inputs.project-id }}
          if [[ $? == 0 ]]; then # All licenses are vetted
            echo "::set-output name=build-succeeded::$(echo 1)"
          else
            echo "::set-output name=build-succeeded::$(echo 0)"
          fi
        else
          mvn ${mvnArgs}
          if [[ $? != 0 ]]; then
            echo "Committers can request a review by commenting '/request-license-review'"
            exit 1
          fi
        fi
